### PR TITLE
upgrade to jsdom 5.6.1 (from previous jsdom 3.x.x)

### PR DESCRIPTION
**Pull request by przeor**

### CODE REVIEW

**Comment by tunerex** [comment]
@przeor Thank you very much for the pull request.
I chose not to use jsdom 3.x.1 because 5.x is not compatible with nodejs?
Did jsdom requirement changed on 5.6.1?

**Comment by koulmomo** [comment]
@przeor 

> Note that as of our 4.0.0 release, jsdom no longer works with Node.js™, and instead requires io.js. You are still welcome to install a release in the 3.x series if you use Node.js™.

from: https://github.com/tmpvar/jsdom/tree/42aa4ec0d8aa9ab3146faa6cfb25a38579d0ff4b#install

**Comment by przeor** [comment]
@tunerex yes, that true that we use iojs in the project ... anyway, it was the fix that our project which was requiring the jsdom 5.6.1 is working with your great lib. It may be useful for other folks out there so maybe it's work to create another branch for iojs & jsdom 5.6.1 users

**Comment by rexk** [comment]
I can think of two possible solution for iojs.
1. Publish both iojs version and nodejs version into npm module using npm scripts
  For example, mocha-mix will be published into `mocha-mix` and `mocha-mix-iojs` with slight alteration of package.json via npm run scripts

2. Polyfill jsdom using following code
```js
global.window = document.parentWindow || document.defaultView;
```
What do you think @koulmomo ?

**Comment by rexk** [comment]
I found `mocha-jsdom` and it is compatible both on iojs and nodejs.
Using same technique I think we can achieve iojs compatibility.

https://www.npmjs.com/package/mocha-jsdom

**Comment by rexk** [comment]
Closing this pull request because #29 resolves the problem.
Package is not published yet.

**Pull request closed without merging**
